"""Added created_time column to tasks

Revision ID: 2de835f6490f
Revises: 4910ace95e13
Create Date: 2022-07-19 01:51:29.282391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de835f6490f'
down_revision = '4910ace95e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'created_time')
    # ### end Alembic commands ###
