"""empty message

Revision ID: bf0f8ee69cdb
Revises: e0ec115cebb4
Create Date: 2022-07-12 17:45:17.530229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf0f8ee69cdb'
down_revision = 'e0ec115cebb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completion_time', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'complition_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('complition_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'completion_time')
    # ### end Alembic commands ###
