"""removed fields from user

Revision ID: fff5d0061ffe
Revises: bf0f8ee69cdb
Create Date: 2022-07-14 21:10:08.284829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff5d0061ffe'
down_revision = 'bf0f8ee69cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_telegram_username_key', 'users', type_='unique')
    op.drop_column('users', 'urgency')
    op.drop_column('users', 'privilege')
    op.drop_column('users', 'todo_list')
    op.drop_column('users', 'not_done')
    op.drop_column('users', 'done')
    op.drop_column('users', 'data_business')
    op.drop_column('users', 'name_business')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_business', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('data_business', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('done', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('not_done', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('todo_list', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('privilege', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('urgency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_telegram_username_key', 'users', ['telegram_username'])
    # ### end Alembic commands ###
